import Head from "next/head";
import Button from "@mui/material/Button";
import { Inter } from "next/font/google";
import { MainLayout } from "@/components/layouts/Mainlayout";
import { EditCvForm } from "@/components/editCvForm/editCvForm";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>CV Generator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <MainLayout editCvForm={<EditCvForm />} cvView={<>CvView</>} />
      </main>
    </>
  );
}
